apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris
      version: v2
  template:
    metadata:
      labels:
        app: tetris
        version: v2
    spec:
      containers:
      - name: tetris
        image: myregistry/tetris:v2
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  labels:
    app: tetris
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: tetris
    version: v2
