----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris-blue
  template:
    metadata:
      labels:
        app: tetris-blue
    spec:
      containers:
      - name: tetris-blue
        image: manojsiriparthi/tetrisv1:6
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-blue
spec:
  selector:
    app: tetris-blue
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000
  type: LoadBalancer
